apiVersion: v1
kind: Service
metadata:
  name: websocket-service
  namespace: websocket
spec:
  selector:
    app: websocket
  type: LoadBalancer
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
