apiVersion: v1
kind: ConfigMap
metadata:
  name: publisher-config
  namespace: publisher
data:
  # Database
  DATABASE_CONN: "postgresql+asyncpg://postgres:wjdqudwo@postgresql.postgresql.svc.cluster.local:5432/shopping"
  
  # DB Connection Pool Settings
  DB_POOL_SIZE: "10"
  DB_MAX_OVERFLOW: "20"
  DB_POOL_RECYCLE: "3600"
  
  # Kafka
  KAFKA_BOOTSTRAP_SERVERS: "kafka-controller-0.kafka-controller-headless.kafka.svc.cluster.local:9092,kafka-controller-1.kafka-controller-headless.kafka.svc.cluster.local:9092,kafka-controller-2.kafka-controller-headless.kafka.svc.cluster.local:9092"
  KAFKA_USER: "user1"
  KAFKA_PASSWORD: "wjdqudwo"
  KAFKA_SASL_MECHANISM: "PLAIN"
  KAFKA_SECURITY_PROTOCOL: "SASL_PLAINTEXT"
  
  # Publisher 설정
  POLL_INTERVAL_SECONDS: "1"
  BATCH_SIZE: "100"
  
  # 로깅
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
