apiVersion: v1
kind: Service
metadata:
  name: publisher-service
  namespace: publisher
spec:
  selector:
    app: publisher
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: metrics
