---
apiVersion: v1
kind: Namespace
metadata:
  name: consumer-analytics
  labels:
    app: shopping
    tier: kafka
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: consumer-analytics-config
  namespace: consumer-analytics
data:
  DATABASE_CONN: "postgresql+asyncpg://postgres:wjdqudwo@postgres-service.postgres.svc.cluster.local:5432/shopping"
  REDIS_URL: "redis://:wjdqudwo@redis-service.redis.svc.cluster.local:6379/0"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service.kafka.svc.cluster.local:9092"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-analytics
  namespace: consumer-analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-analytics
  template:
    metadata:
      labels:
        app: consumer-analytics
    spec:
      containers:
      - name: consumer-analytics
        image: 192.168.19.143:5000/shopping-consumer-analytics:latest
        envFrom:
        - configMapRef:
            name: consumer-analytics-config
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: consumer-analytics-service
  namespace: consumer-analytics
spec:
  selector:
    app: consumer-analytics
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: metrics
