apiVersion: v1
kind: ConfigMap
metadata:
  name: consumer-analytics-config
  namespace: consumer-analytics
data:
  DATABASE_CONN: "postgresql+asyncpg://postgres:wjdqudwo@postgresql.postgresql.svc.cluster.local:5432/shopping"
  REDIS_URL: "redis://:wjdqudwo@redis-master.redis.svc.cluster.local:6379/0"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-controller-0.kafka-controller-headless.kafka.svc.cluster.local:9092,kafka-controller-1.kafka-controller-headless.kafka.svc.cluster.local:9092,kafka-controller-2.kafka-controller-headless.kafka.svc.cluster.local:9092"
