apiVersion: v1
kind: Service
metadata:
  name: consumer-analytics-service
  namespace: consumer-analytics
spec:
  selector:
    app: consumer-analytics
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: metrics
