apiVersion: v1
kind: ConfigMap
metadata:
  name: consumer-stock-config
  namespace: consumer-stock
data:
  DATABASE_CONN: "postgresql+asyncpg://postgres:wjdqudwo@post-postgresql.post.svc.cluster.local:5432/shopping"
  REDIS_URL: "redis://:wjdqudwo@redis-master.redis.svc.cluster.local:6379/0"
  KAFKA_BOOTSTRAP_SERVERS: "kafka.kafka.svc.cluster.local:9092"
