apiVersion: v1
kind: Service
metadata:
  name: consumer-stock-service
  namespace: consumer-stock
spec:
  selector:
    app: consumer-stock
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: metrics
