apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shopping
  namespace: front
  annotations:
    haproxy.org/backend-config-snippet: |
      http-response replace-value Location ^http://(.*)$ https://\1
spec:
  ingressClassName: haproxy
  tls:
  - hosts:
    - shopping.project.com
    secretName: shopping
  rules:
  - host: shopping.project.com
    http:
      paths:
      - backend:
          service:
            name: frontend-service
            port:
              number: 80
        path: /
        pathType: Prefix
